export const SAN_DIEGO_COUNTY_CITIES = [
  "San Diego",
  "Chula Vista",
  "El Cajon",
  "National City",
  "Escondido",
  "La Mesa",
  "Encinitas",
  "Carlsbad",
  "Oceanside",
  "Vista",
  "San Marcos",
  "Poway",
  "Santee",
  "Coronado",
  "Imperial Beach",
  "Lemon Grove",
  "La Jolla",
  "Pacific Beach",
  "Clairemont",
  "Mira Mesa",
  "Rancho Bernardo",
  "Del Mar",
  "Solana Beach",
];
